### PR TITLE
Update cassandra_migrations.gemspec

### PR DESCRIPTION
**Pull request by ook**
Upgrade rake dependency

### CODE REVIEW

**Comment by hugohenley** [comment]
@ook that might break production since we don't specify a version there

`gem 'cassandra_migrations', git: 'https://github.com/followanalytics/cassandra_migrations.git'`

**Review by hugohenley — CHANGES_REQUESTED** [review]
We need to be able to specify a version on the API's Gemfile

**Comment by ook** [comment]
Hell no! Why on earth are we still so into anti-patterns? >_<

**Comment by ook** [comment]
So I guess I have to prepare an hotfix for `master` T_T

**Comment by ook** [comment]
The hotfix is in production, I merge that PR.

**Pull request merged**
